const TOKEN_URL="https://oauth2.googleapis.com/token";
const SCOPE="https://www.googleapis.com/auth/spreadsheets";
const SHEET_MAP={movement:env=>env.SHEET_ID_INVENTORY,cycle_count:env=>env.SHEET_ID_INVENTORY};
const SHEET_WHITELIST=new Set(["Movement","Cycle Count"]);
const GRID_SHEET_ID={"Movement":0,"Cycle Count":0};
const toB64=(i)=>btoa(typeof i==="string"?i:JSON.stringify(i)).replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_");
const pemToBuf=p=>{const c=String(p||"").replace(/\\n/g,"\n").replace("-----BEGIN PRIVATE KEY-----","").replace("-----END PRIVATE KEY-----","").replace(/\s/g,"");const b=atob(c);const u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return u.buffer;};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8"}});
async function token(env){const now=Math.floor(Date.now()/1000);const unsigned=`${toB64({alg:"RS256",typ:"JWT"})}.${toB64({iss:env.GOOGLE_CLIENT_EMAIL,scope:SCOPE,aud:TOKEN_URL,exp:now+3600,iat:now})}`;const key=await crypto.subtle.importKey("pkcs8",pemToBuf(env.GOOGLE_PRIVATE_KEY),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,new TextEncoder().encode(unsigned));let bin="";new Uint8Array(sig).forEach(b=>bin+=String.fromCharCode(b));const jwt=`${unsigned}.${btoa(bin).replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_")}`;const r=await fetch(TOKEN_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion:jwt})});const d=await r.json();if(!r.ok||!d.access_token)throw new Error(d.error_description||d.error||"Gagal membuat access token");return d.access_token;}
async function getSheetMeta(sheetId,access,name){const res=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${sheetId}?fields=sheets(properties(sheetId,title))`,{headers:{Authorization:`Bearer ${access}`}});const data=await res.json();if(!res.ok)throw new Error(data.error?.message||"Gagal ambil metadata sheet");const s=(data.sheets||[]).find(x=>x.properties?.title===name);if(!s)throw new Error("sheetName tidak ditemukan");return s.properties.sheetId;}
export async function onRequestDelete({request,env}){try{const b=await request.json();const {sheetKey,sheetName,rowNumber}=b||{};if(!SHEET_MAP[sheetKey])return json({success:false,message:"sheetKey tidak valid"},400);if(!SHEET_WHITELIST.has(sheetName))return json({success:false,message:"sheetName tidak valid"},400);if(!Number.isInteger(rowNumber)||rowNumber<=1)return json({success:false,message:"rowNumber wajib > 1"},400);const ss=SHEET_MAP[sheetKey](env);if(!ss)return json({success:false,message:"Sheet tidak ditemukan"},400);const access=await token(env);const gid=await getSheetMeta(ss,access,sheetName);const res=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${ss}:batchUpdate`,{method:"POST",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({requests:[{deleteDimension:{range:{sheetId:gid,dimension:"ROWS",startIndex:rowNumber-1,endIndex:rowNumber}}}]})});const data=await res.json();if(!res.ok)return json({success:false,message:data.error?.message||"Gagal hapus row"},res.status);return json({success:true,message:"Row berhasil dihapus"});}catch(err){return json({success:false,message:err?.message||"Internal server error"},500);}}
